version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_PORT=8000
      - WORKERS=2
      # Cloud Database
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      # Cloud API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLOUD_KEY=${GOOGLE_CLOUD_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./google-service-account.json:/app/google-service-account.json:ro
    networks:
      - iseetutor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://localhost:8000/api
        - REACT_APP_WS_URL=ws://localhost:8000/ws
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - iseetutor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  iseetutor-network:
    driver: bridge