"""Update Question and Content models for ISEE import

Revision ID: b9413c9f4aa4
Revises: cc8b1c1a8283
Create Date: 2025-07-14 11:27:32.155321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9413c9f4aa4'
down_revision: Union[str, None] = 'cc8b1c1a8283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('text_content', sa.Text(), nullable=True))
    op.add_column('content', sa.Column('content_metadata', sa.JSON(), nullable=True))
    op.alter_column('content', 'subject',
               existing_type=postgresql.ENUM('MATH', 'READING', 'VOCABULARY', 'VERBAL_REASONING', 'QUANTITATIVE_REASONING', 'GENERAL', name='subject'),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('content', 'grade_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('content', 'topics')
    op.drop_column('content', 'extra_data')
    op.add_column('questions', sa.Column('difficulty_level', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('question_metadata', sa.JSON(), nullable=True))
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'tags')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'choices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('choices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'question_metadata')
    op.drop_column('questions', 'time_limit')
    op.drop_column('questions', 'difficulty_level')
    op.add_column('content', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('content', sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('content', 'grade_level',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('content', 'subject',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('MATH', 'READING', 'VOCABULARY', 'VERBAL_REASONING', 'QUANTITATIVE_REASONING', 'GENERAL', name='subject'),
               existing_nullable=True)
    op.drop_column('content', 'content_metadata')
    op.drop_column('content', 'text_content')
    # ### end Alembic commands ###
